### PR TITLE
Add Stellar client

### LINKED ISSUE #52: Add TFT on Stellar wallet
With the transition of TFT from tfchain to the Stellar platform, Jumpscale needs to support this.
Python examples of keycreation, account activation, balance checks and payments are available at https://github.com/threefoldtech/rivine/tree/master/research/stellar/examples/python

### PR DESCRIPTION
**Pull request by DylanVerstraete**

### CODE REVIEW

**Comment by robvanmieghem** [comment]
@xmonader is there something still blocking this PR?

**Comment by robvanmieghem** [comment]
@DylanVerstraete Is the faucetclient required to be in the generic jumpscalelibs?

**Review by xmonader — APPROVED** [review]

**Comment by xmonader** [comment]
@robvanmieghem No, not really. I already gave @DylanVerstraete some comments which I see they were applied :) I'm leaving the logic of stellar to you. Will merge once your approve

**Review by robvanmieghem — APPROVED** [review]
I removed the faucet client and adapted the changes in the commits before that, LGTM

**Pull request merged**
